name: Matrix Playground

on: push

jobs:
  one:
    name: Cypress tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['billing', 'staff-portal']
    steps:
      - name: Run cypress for billing
        if: matrix.project == 'billing'
        run: echo 'run specs for ${{ matrix.project }}'

      - name: Run cypress for staff-portal
        if: matrix.project == 'staff-portal'
        run: echo 'run specs for ${{ matrix.project }}'

  second_job:
    name: Comment based job
    runs-on: ubuntu-latest
    steps:
      # - name: See params
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "${GITHUB_CONTEXT}"
      - name: Parse the comment
        run: echo 'COMMENT BODY = ${{ github.event.comment.body }}'
